### ISSUE TITLE
Entity Component System

### ISSUE THREAD

**Issue by davedissian** [davedissian/dawnengine#2]
At the moment, the engine is very "hierarchy" based when it comes to game object. This should eventually be moved to a more flat Component based design.

**Comment by davedissian** [comment]
Starting work on this in the develop branch

**Comment by dgavedissian** [comment]
> Please consider two features for yours:
> 1) Dependency resolution during runtime, not every frame. Every ECS I've looked at filters events every time you call world.update() instead of caching them and it's slow.
> 2) Support polymorphic systems

**Comment by dgavedissian** [comment]
Decided to integrate [Ontology](https://github.com/TheComet93/ontology)
